version: '3'
services: 
  web:
    image: php-nginx-standard
    build: container
    ports: 
      - '443:443'
      - '80:80'
    container_name: eumaios-backend
    volumes:
      - "/example:/data/www"
      - "/example/localcerts:/etc/ssl/localcerts"